// Shared portfolio project data — used by Resume project chips, Portfolio index, and Project pages
const PORTFOLIO_PROJECTS = [
  {
    slug: 'parachute',
    title: 'Mobile Parachute Mix Reality',
    client: 'UpTrans Teknologi, Bandung Simulator Group',
    role: '3D Designer · Lead Design · Game Tester',
    period: '2025',
    studio: 'UpTrans Teknologi · Cube Studio',
    discipline: ['3D', 'VR', 'Mixed Reality', 'Simulation'],
    cover: 'oklch(0.80 0.06 145)',
    coverDeep: 'oklch(0.55 0.08 145)',
    summary: 'A mixed-reality parachute simulation system with physical motion rig, VR headset, and instructor control station — saving the Air Force 500M+ Rupiah per training flight.',
    metric: '500M+',
    metricLabel: 'Rupiah saved per training flight',
    href: 'Case-Parachute.html',
    featured: true,
  },
  {
    slug: 'vlux',
    title: 'Lighting Kungfu',
    client: 'Cube Studio (in-house product)',
    role: 'Product Designer · UI/UX Designer',
    period: '2025 — Ongoing',
    studio: 'Cube Studio',
    discipline: ['Desktop App', 'VR', 'B2B', 'Architecture'],
    cover: 'oklch(0.78 0.06 60)',
    coverDeep: 'oklch(0.50 0.10 55)',
    summary: 'Desktop lighting design tool built on Unreal Engine 5. Progressive disclosure serves both professionals and homeowners — with VR walkthrough.',
    metric: '2',
    metricLabel: 'User types in one product',
    href: 'Case-Vlux.html',
    featured: false,
  },
  {
    slug: 'gotechup',
    title: 'GoTechUp URC',
    client: 'GoTechUp Malaysia & Singapore',
    role: 'UI/UX Designer · Level Designer · 3D Designer',
    period: '2023 — Ongoing',
    studio: 'GoTechUp',
    discipline: ['EdTech', 'Gamification', 'Web App', 'Multi-country'],
    cover: 'oklch(0.74 0.06 140)',
    coverDeep: 'oklch(0.52 0.10 135)',
    summary: 'A gamified web-based robotics competition platform — 21 levels across 6 countries, no hardware required.',
    metric: '21',
    metricLabel: 'Levels across 6 countries',
    href: 'Case-Edutech.html',
    featured: false,
  },
  {
    slug: 'pataland',
    title: 'PataLand',
    client: 'In-house (Paradimensi)',
    role: 'Product Designer · Lead Design · Visual Designer · Game Designer',
    period: '2022 — 2024',
    studio: 'Cube Studio',
    discipline: ['Metaverse', 'Social', 'Entertainment', 'Cross-platform'],
    cover: 'oklch(0.72 0.06 145)',
    coverDeep: 'oklch(0.48 0.08 140)',
    summary: 'A web-based social-entertainment metaverse — virtual concerts, avatar identity, and persistent social spaces across 5 Southeast Asian countries.',
    metric: '5',
    metricLabel: 'Countries reached',
    href: 'Case-Pataland.html',
    featured: false,
  },
  {
    slug: 'metaverse',
    title: 'Mobile Metaverse',
    client: 'Techpolitan',
    role: 'Business Development · Project Manager · 3D Design',
    period: '2022 — 2023',
    studio: 'Techpolitan',
    discipline: ['Mobile', 'Metaverse', 'Social', 'XR'],
    cover: 'oklch(0.70 0.08 310)',
    coverDeep: 'oklch(0.48 0.13 300)',
    summary: 'A mobile Metaverse integrating brands under PT. Walden Global Service into one social-ecosystem to promote and sell digital goods and services.',
    metric: '—',
    metricLabel: 'Brand integration platform',
    href: 'Case-Metaverse.html',
    featured: false,
  },
];

window.PORTFOLIO_PROJECTS = PORTFOLIO_PROJECTS;
