// Per-project content for the immersive project pages.
// Each HTML page sets window.PROJECT_SLUG before loading this file + case-study-app.jsx.

const ALL_PROJECT_CONTENT = {

  parachute: {
    hero: {
      slug: 'parachute',
      title: 'Mobile Parachute\nMix Reality',
      tagline: 'Full-body simulation, from cabin to landing zone.',
      cover: 'oklch(0.80 0.06 145)',
      coverDeep: 'oklch(0.42 0.08 145)',
      client: 'UpTrans Teknologi, Bandung Simulator Group',
      role: '3D Designer · Lead Design · Game Tester',
      team: 'UpTrans Teknologi (main contractor) · Cube Studio (VR software & integration)',
      period: 'March 2025 — July 2025 · 5 months',
      platform: 'VR Headset · Motion Rig · Control Station',
      discipline: ['3D', 'VR', 'Mixed Reality', 'Simulation'],
      tools: 'Figma, Blender, Adobe, Unity, CorelDraw, Notion',
      metric: '500M+',
      metricLabel: 'Rupiah saved per training flight',
    },
    tags: 'mixed reality · simulation',
    heroSvg: 'parachute',
    problem: {
      title: 'Each training flight costs the Air Force at least 500 million Rupiah.',
      statValue: 500, statSuffix: 'M+', statUnit: 'Rupiah / flight',
      description: 'Training parachutists requires real aircraft, real fuel (Avtur), and real risk. Weather delays compound the expense. And cadets face their first jump with no physical rehearsal — the gap between classroom theory and a live exit is enormous.',
      constraints: [
        'Must replicate real-world parachute operations as closely as possible',
        'Full-body experience — not just visual VR, physical motion rig required',
        'Instructor-controlled from a dedicated station with CCTV and monitoring',
        'Training zones modeled from real airports (10 km × 10 km each)',
        'Built and shipped in 5 months — non-negotiable deadline',
      ],
      summary: 'The academy needed a simulation system that replicates real parachute operations closely enough to build muscle memory — without the aircraft.',
    },
    process: {
      title: 'Five steps from a meeting room to a working rig.',
      sub: 'Each phase built on the previous — no handoffs, no gaps.',
      steps: [
        { n: '01', label: 'Application flow design', body: 'Mapped the entire system flow — from login and credential validation through scenario configuration, jumper selection, calibration, and the jump itself. Supports one-jumper and two-jumper modes, with scenario editing and jump record review.' },
        { n: '02', label: 'Environment research', body: 'Modeled training zones from real airports — Sulaiman Air Force Base, Halim Perdana Kusuma Airport, and Adisutjipto International Airport. Each zone covers a 10 km × 10 km area measured from the jump point to ensure the parachutist gains a clear understanding of the operational environment.' },
        { n: '03', label: '3D & VR development', body: 'Built the simulation environment in Unity with Blender for 3D assets. The VR experience needed to feel real enough that muscle memory would transfer — not a game, a training tool.' },
        { n: '04', label: 'Hardware integration', body: 'The hardware system elevates and rotates the player in response to control inputs, while delivering immersive environmental effects such as wind and water sprays. The control station continuously monitors all movements and securely logs data within a centralized database.' },
        { n: '05', label: 'Control station UI', body: 'All operations are managed centrally from the control station. Parachutists don\'t require a UI — all instructions are communicated through audio and visual channels. The instructor configures jump scenarios, assigns parachutists, calibrates hardware, and oversees the entire process.' },
      ],
    },
    solution: {
      title: 'Hardware, software, and control — one integrated system.',
      heroLabels: ['Jumper Monitor', 'Scenario Editor', 'Calibration'],
      features: [
        { tag: 'The hardware', title: 'Full-body motion rig.', body: 'A physical harness system that elevates and rotates the trainee in response to VR inputs, with wind and water spray for immersive environmental effects. The most advanced parachute simulator built for Indonesia\'s Air Force.', accentKey: 'green' },
        { tag: 'For instructors', title: 'Complete control station.', body: 'Instructors configure scenarios, assign jumpers, monitor via CCTV, calibrate hardware, and review results — all from one centralized station. Screens include Jumper Monitor, CCTV, Result, Calibrating, and Scenario Edit pages.', accentKey: 'yellow' },
        { tag: 'For cadets', title: 'Audio-visual guided experience.', body: 'Parachutists receive all instructions through audio and visual channels inside the VR headset. No UI to learn — just follow the training and build muscle memory. Every activity is recorded and stored for evaluation before putting students in a real jump.', accentKey: 'pink' },
      ],
    },
    gallery: [
      { label: 'VR simulation environment — cadet view' },
      { label: 'Motion rig hardware' },
      { label: 'Control station — monitoring panel' },
      { label: 'Environment map — Sulaiman AFB' },
      { label: 'Application flow diagram' },
    ],
    outcome: {
      title: 'A simulation system that saves hundreds of millions per flight.',
      stats: [
        { val: 500, suffix: 'M+', label: 'Rupiah saved per training flight', accentKey: 'accent' },
        { val: 3, suffix: '', label: 'Real airports modeled (10 km × 10 km)', accentKey: 'green' },
        { val: 5, suffix: ' mo', label: 'From kick-off to delivery', accentKey: 'yellow' },
      ],
      impactQuote: '"This simulator saves Indonesia Air Force at least 500 millions Rupiah per flight to train academy students."',
      impactNote: '*Estimated with Avtur\'s price plus number of students',
    },
    reflection: {
      title: 'What I learned.',
      cards: [
        { heading: 'The control station matters most.', body: 'Instructors are the real power users. If they can\'t configure scenarios, monitor cadets, and calibrate hardware confidently, the whole system fails regardless of how good the VR feels.' },
        { heading: 'Calibration is UX.', body: 'Calibrating the rig before every session is a must-do process before jump. Getting it wrong means the physical feedback won\'t match the visual. I spent more time on that flow than I expected, and it was worth it.' },
        { heading: 'Hardware changes everything.', body: 'This was my first project integrating VR software with physical hardware — motors, harnesses, environmental effects. The feedback loop between physical and digital is a completely different design challenge.' },
        { heading: 'Scoping as a sub-contractor.', body: 'I owned the VR software and integration layer, but had to coordinate closely with UpTrans Teknologi on hardware constraints and the academy on training requirements. Clear boundaries made the 5-month timeline possible.' },
      ],
    },
  },

  pataland: {
    hero: {
      slug: 'pataland',
      title: 'PataLand',
      tagline: 'Immerse your musical experience.',
      cover: 'oklch(0.72 0.06 145)',
      coverDeep: 'oklch(0.38 0.08 140)',
      client: 'In-house (Paradimensi)',
      role: 'Product Designer · Lead Design · Visual Designer · Game Designer',
      team: 'Cube Studio (in-house) · FUTR Asia & Surge (partners)',
      period: '2022 — 2024 · 2 years',
      platform: 'Web · VR Headset · Desktop · Mobile (cross-platform)',
      discipline: ['Metaverse', 'Social', 'Entertainment', 'Cross-platform'],
      tools: 'Figma, Blender, Adobe, Unity, CorelDraw, Trello',
      metric: '836',
      metricLabel: 'Registered accounts',
    },
    tags: 'metaverse · social entertainment',
    heroSvg: 'generic',
    problem: {
      title: 'Online entertainment was stuck in passive mode.',
      statValue: 836, statSuffix: '', statUnit: 'Registered accounts',
      description: 'PataLand is a web-based Social Entertainment Metaverse where people can gather to socialize while enjoying entertainment such as virtual concerts or exciting games and engaging with their beloved performers and fellow die-hard fans. The challenge was to design a platform that let users be active participants — not just audiences — across a cross-platform experience that had to work on VR headsets, desktops, and mobile devices.',
      constraints: [
        'Web-based — no app install, must run in browser across device tiers',
        'Cross-platform: VR headset, desktop, and mobile with consistent experience',
        'Social features (chat, groups) alongside entertainment features (concerts, games)',
        'Manage up to 10 booths per island with dashboard controls',
        'Character customization with purchasable items via in-game currency',
      ],
      summary: 'The platform needed to make users feel like they were in the room — not watching through a screen.',
    },
    process: {
      title: 'From concept to 4 collaborated artists — a 2-year design lifecycle.',
      sub: 'As Lead Designer, I applied a data-driven approach to every decision.',
      steps: [
        { n: '01', label: 'Data-driven UX architecture', body: 'Architected a user-behavior tracking system using custom triggers. By analyzing interaction heatmaps and navigation patterns, I provided actionable insights that allowed the development team to refine the UX.' },
        { n: '02', label: 'Product lifecycle management', body: 'Managed the product lifecycle by translating stakeholder requirements into functional specifications and UX logic. Led technical discussions with developers to ensure seamless system integration before assigning tasks to the creative team.' },
        { n: '03', label: 'Character & environment design', body: 'Redesigned characters with more defining silhouettes and uniform proportions to make customization easier from both design and dev perspectives. Rearranged map layouts to create smoother and more engaging flows around the island.' },
        { n: '04', label: 'Technical optimization', body: 'Implemented reusable universal textures, spatial download with level of detail, and universal body presets. Improved shaders while minimizing vertices used, and made the UI clean while improving overall performance.' },
        { n: '05', label: 'PataLawan! VS — cross-platform game', body: 'Developed a Web (Mobile & Desktop) vs Virtual Reality game launched at INACON 2024. Balanced damage and buffs so both players had equal chance of winning, with power-ups including extra ammunition, cannons, healing, and speed boosts.' },
      ],
    },
    solution: {
      title: 'A metaverse where the event is the UI.',
      heroLabels: ['Concert Hall', 'Character Builder', 'Island Dashboard'],
      features: [
        { tag: 'Social layer', title: 'Custom your character.', body: 'Character customization with purchasable items via in-game currency. The design went more straightforward with defining silhouettes and uniform proportions — easier to customize from both design and development perspectives.', accentKey: 'green' },
        { tag: 'Entertainment', title: 'Watch your favorite artist.', body: 'Virtual concerts with 4 collaborated artists. Social chat and group features let fans engage with performers and fellow die-hard fans in real-time, across VR, desktop, and mobile.', accentKey: 'yellow' },
        { tag: 'Management', title: 'Manage island with dashboard.', body: 'Up to 10 booths per island, all manageable through a dashboard. Fun games, social activities, and cross-platform capabilities — accessible on VR headset, desktop, and mobile.', accentKey: 'pink' },
      ],
    },
    gallery: [
      { label: 'Virtual concert — stage view' },
      { label: 'Character customization system' },
      { label: 'Island landscape environment' },
      { label: 'PataLawan! VS gameplay' },
      { label: 'Social media & publicity materials' },
    ],
    outcome: {
      title: 'A social-entertainment metaverse shipped across Southeast Asia.',
      stats: [
        { val: 836, suffix: '', label: 'Registered accounts', accentKey: 'accent' },
        { val: 10, suffix: '+', label: 'Fun & social activities', accentKey: 'green' },
        { val: 4, suffix: '', label: 'Collaborated artists', accentKey: 'yellow' },
      ],
      impactQuote: '"Up to 10 booths per island, 4 collaborated artists, and 836 registered accounts — with many more as guest users."',
      impactNote: '106 social media posts · 281 followers · 4 events attended · 3.32% average ER rate',
    },
    reflection: {
      title: 'What I learned.',
      cards: [
        { heading: 'Data-driven design leadership.', body: 'Architecting a custom tracking system with interaction heatmaps and navigation patterns gave me actionable insights — not just metrics. It changed how I led design decisions, grounding every UX choice in real user behavior.' },
        { heading: 'Balancing fidelity and performance.', body: 'Every feature had to remain visually intuitive while being technically optimized for web performance. Maintaining high-end fidelity across VR, desktop, and mobile required constant trade-offs between what looks good and what runs well.' },
        { heading: 'Cross-platform game design.', body: 'PataLawan! VS taught me how to balance asymmetric gameplay between Web and VR players. Making both sides feel fair while leveraging each platform\'s strengths was the hardest design challenge on the project.' },
        { heading: 'Social media as product.', body: 'Managing PataLand\'s social presence — 106 posts, 4 events attended — wasn\'t separate from the product. The social media templates and publicity materials were part of the user acquisition funnel, not an afterthought.' },
      ],
    },
  },

  vlux: {
    hero: {
      slug: 'vlux',
      title: 'Lighting Kungfu',
      tagline: 'Design indoor lighting with real-time render.',
      cover: 'oklch(0.78 0.06 60)',
      coverDeep: 'oklch(0.40 0.08 55)',
      client: 'Cube Studio (in-house product)',
      role: 'Product Designer · UI/UX Designer',
      team: 'Cube Studio (in-house)',
      period: '2025 — Ongoing',
      platform: 'Desktop (Windows) · VR Integrated',
      discipline: ['Desktop App', 'VR', 'B2B', 'Architecture'],
      tools: 'Figma, Blender, Unreal Engine 5, CorelDraw, Notion',
      metric: '2',
      metricLabel: 'User types served in one product',
    },
    tags: 'lighting design · desktop + VR',
    heroSvg: 'generic',
    problem: {
      title: 'Professional tools terrify casual users. Consumer tools frustrate professionals.',
      statValue: 2, statSuffix: '', statUnit: 'User types',
      description: 'Lighting Kungfu by Vlux is a software specifically for designing indoor lighting with real-time render. Developed with Unreal Engine 5 to achieve maximum realistic level, this software is intended for experts for serious work and technical testing or casual users who like to design something. The challenge was to build one product that could serve both without compromising either.',
      constraints: [
        'One product, two radically different user types: lighting experts and casual designers',
        'Real-time rendering at professional accuracy — powered by Unreal Engine 5',
        'VR integration for immersive walkthrough and in-VR design capabilities',
        'Monetization through subscriptions, marketplace, and premium features',
      ],
      summary: 'The question wasn\'t "how do we hide complexity" — it was "how do we respect two different definitions of what this tool should do."',
    },
    process: {
      title: 'Progressive disclosure as a product philosophy.',
      sub: 'Not just a pattern — a way of thinking about two users in one product.',
      steps: [
        { n: '01', label: 'Feature architecture', body: 'Mapped the entire feature system across four clusters: Render-related (real-time render, lighting heat map, lighting animation, AI), Files/library (upload, surface textures, marketplace), Room Designing (furniture placement, UGC, templates, multiple rooms), and VR-related (ticketing, virtual showroom, environment simulation).' },
        { n: '02', label: 'Lighting heat map', body: 'Designed the heat map feature that displays how strongly light hits a surface, allowing serious users to get accurate readings of their lighting design. This became the key differentiator between casual and expert modes.' },
        { n: '03', label: 'Object & room system', body: 'The system empowers users to design not only the lighting but also the objects within their room, providing a practical and realistic sense of how the final design will look. Users can place furniture, choose surface textures, and work with templates and presets.' },
        { n: '04', label: 'VR experience integration', body: 'Integrating virtual reality significantly elevates the user experience — enabling deeper exploration and immersion. Beyond navigating spaces, users can design and build their lighting room directly in VR, leveraging the full suite of features available in the desktop version.' },
        { n: '05', label: 'Monetization strategy', body: 'Designed five revenue streams: locked features subscription (tiered), property/furniture marketplace, advance rooms, co-designing (team collaboration with live client review), and custom services. Focused on making monetization feel seamless and non-intrusive to foster long-term adoption.' },
      ],
    },
    solution: {
      title: 'One tool. Two users. Real-time render.',
      heroLabels: ['Heat Map', 'Object System', 'VR Walkthrough'],
      features: [
        { tag: 'For experts', title: 'Lighting heat map.', body: 'Displays how strongly the light hits a surface, allowing users — especially those who are more serious — to get accurate readings of their lighting design. Combines with lighting animation and advanced shader controls.', accentKey: 'green' },
        { tag: 'For everyone', title: 'Add & arrange objects.', body: 'Design not only the lighting but also the objects within your room. Choose from the marketplace, upload your own, or use templates and presets — providing a practical and realistic sense of how the final design will look.', accentKey: 'yellow' },
        { tag: 'Immersion', title: 'VR experience integrated.', body: 'Walk through your lighting design in VR. Beyond simply navigating, users can design and build their lighting room directly in VR, leveraging the full suite of desktop features — deeper exploration and immersion within newly created spaces.', accentKey: 'pink' },
      ],
    },
    gallery: [
      { label: 'Real-time render — living room' },
      { label: 'Lighting heat map visualization' },
      { label: 'Object placement interface' },
      { label: 'VR walkthrough experience' },
      { label: 'Feature relationship diagram' },
    ],
    outcome: {
      title: 'A lighting design tool that respects both kinds of user.',
      stats: [
        { val: 2, suffix: '', label: 'User types in one product', accentKey: 'accent' },
        { val: 5, suffix: '', label: 'Revenue streams designed', accentKey: 'green' },
        { val: 4, suffix: '', label: 'Feature clusters architected', accentKey: 'yellow' },
      ],
      impactQuote: '"My work often focuses on identifying strategic opportunities where companies can offer goods or services in ways that feel seamless and non-intrusive to users."',
      impactNote: 'Currently in active development at Cube Studio. These monetization models were initial suggestions from the product design phase.',
    },
    reflection: {
      title: 'What I learned.',
      cards: [
        { heading: 'Disclosure is a philosophy.', body: 'Designing for two radically different users in one product forced me to treat progressive disclosure as a philosophy, not a pattern. It\'s not about hiding — it\'s about respecting different definitions of purpose.' },
        { heading: 'Market knowledge is critical.', body: 'Designing monetization that encourages voluntary engagement and fosters long-term adoption requires deep market knowledge. Understanding how users perceive value — not just what they\'ll pay for — shaped every revenue decision.' },
        { heading: 'Feature relationships matter.', body: 'Mapping how features interconnect across render, files, room design, and VR revealed dependencies that a flat feature list would miss. The node-map approach became essential for roadmap prioritization.' },
        { heading: 'VR as validation, not feature.', body: 'The VR walkthrough isn\'t a gimmick — it\'s the moment where the user validates their work in the most intuitive way possible. That makes it the most important feature, not the flashiest.' },
      ],
    },
  },

  gotechup: {
    hero: {
      slug: 'gotechup',
      title: 'GoTechUp URC',
      tagline: 'Universal Robotics Challenge — no hardware required.',
      cover: 'oklch(0.74 0.06 140)',
      coverDeep: 'oklch(0.38 0.08 135)',
      client: 'GoTechUp Malaysia & Singapore',
      role: 'UI/UX Designer · Level Designer · 3D Designer',
      team: 'GoTechUp (client) · In-house design & dev',
      period: '2023 — Ongoing',
      platform: 'Web browser · Cross-platform',
      discipline: ['EdTech', 'Gamification', 'Web App', 'Multi-country'],
      tools: 'Figma, Blender, Notion',
      metric: '21',
      metricLabel: 'Levels designed across 6 countries',
    },
    tags: 'edtech · gamification',
    heroSvg: 'generic',
    problem: {
      title: 'Robotics education stops at the classroom door.',
      statValue: 6, statSuffix: '', statUnit: 'Countries',
      description: 'GoTechUp is a web-based gamified simulation software aimed at enhancing learning the foundation through robotics education based in Malaysia & Singapore. It is a Learning Management System that transforms training and learning experiences into interactive, immersive experiences that simplify complex concepts, making it more enjoyable and less intimidating.',
      constraints: [
        'Must run in a school browser — no app install, no special hardware',
        'Content for different age bands across 6 countries',
        'Annual international competition with 3-sequence maps within 120 minutes',
        'Compact, modular map structure to streamline robot movement and minimize time constraints',
      ],
      summary: 'GoTechUp needed a web-based platform that could simulate robotics challenges gamefully — leveled by age, accessible without hardware, and scalable to international competition.',
    },
    process: {
      title: '21 levels designed across 6 countries.',
      sub: 'A premier international competition that welcomes robotics enthusiasts of all ages.',
      steps: [
        { n: '01', label: 'Competition format design', body: 'The Universal Robotics Challenge is a premier international competition. Participants are tasked with completing 3-sequence maps within 120 minutes, navigating challenges such as object-matching, item collection, and obstacle avoidance.' },
        { n: '02', label: 'Level architecture', body: 'Designed 21 total levels across map types including City Night, City Day, and MRT Station. The maps use compact, modular structures to ensure streamlined robot movement and minimize time constraints for players and developers alike.' },
        { n: '03', label: '3D environment design', body: 'Built 3D simulated robotics environments in Blender — modular arenas that could be reassembled for different challenge types. Designed to render fast in-browser on mid-range school hardware.' },
        { n: '04', label: 'GTU+ Dashboard', body: 'GTU+ serves as the central hub for the GTU ecosystem, integrating a sales platform, administrative dashboard, and virtual classroom. Educators monitor student progress within custom classes and streamline support via an integrated ticketing system.' },
        { n: '05', label: 'International rollout', body: 'Rolled out to 6 different countries with 100+ participants worldwide. Students master coding logic through structured courses, and both teachers and students access performance analytics for data-driven evaluations.' },
      ],
    },
    solution: {
      title: 'The competition came to the classroom.',
      heroLabels: ['Level Browser', 'Challenge Arena', 'GTU+ Dashboard'],
      features: [
        { tag: 'Competition', title: '21 levels, 3 map types.', body: 'City Night, City Day, and MRT Station environments. Each level introduces challenges like object-matching, item collection, and obstacle avoidance — completed in 3-sequence maps within 120 minutes.', accentKey: 'green' },
        { tag: 'Platform', title: 'GTU+ central hub.', body: 'Integrates a sales platform, administrative dashboard, and virtual classroom. Educators monitor student progress, streamline technical support via ticketing, and students master coding logic through structured courses.', accentKey: 'yellow' },
        { tag: 'Analytics', title: 'Data-driven evaluation.', body: 'Both teachers and students access performance analytics to facilitate data-driven evaluations. The platform provides a comprehensive learning environment that simplifies complex robotics concepts.', accentKey: 'pink' },
      ],
    },
    gallery: [
      { label: 'Level browser — challenge selection' },
      { label: '3D arena — City Night map' },
      { label: 'GTU+ Dashboard — student progress' },
      { label: 'Competition leaderboard' },
      { label: 'Modular arena components (Blender)' },
    ],
    outcome: {
      title: 'A gamified LMS that brought robotics competition to 6 countries.',
      stats: [
        { val: 21, suffix: '', label: 'Total levels designed', accentKey: 'accent' },
        { val: 6, suffix: '', label: 'Different countries', accentKey: 'green' },
        { val: 100, suffix: '+', label: 'Participants worldwide', accentKey: 'yellow' },
      ],
      impactQuote: '"The Universal Robotics Challenge is a premier international competition that welcomes robotics enthusiasts of all ages."',
      impactNote: 'Annual competition — ongoing since 2023',
    },
    reflection: {
      title: 'What I learned.',
      cards: [
        { heading: 'Gamification done right.', body: 'This project proved that gamification, done right, doesn\'t just make things fun — it transforms training and learning into interactive, immersive experiences that simplify complex concepts and make them less intimidating.' },
        { heading: 'Fairness is a design problem.', body: 'The same level had to feel fair across 6 countries with different curricula and device capabilities. Difficulty calibration was a design challenge, not a tuning afterthought.' },
        { heading: 'Modular maps save everyone.', body: 'Compact, modular map structures streamlined both robot movement for players and development time for the team. One design decision that optimized for both audiences simultaneously.' },
        { heading: 'The dashboard is the other product.', body: 'GTU+ is as important as the game itself. Educators need to monitor progress, manage classes, and evaluate data — without that layer, the competition is just a game, not an educational platform.' },
      ],
    },
  },

  metaverse: {
    hero: {
      slug: 'metaverse',
      title: 'Mobile Metaverse',
      tagline: 'Integrating brands into one social ecosystem.',
      cover: 'oklch(0.70 0.08 310)',
      coverDeep: 'oklch(0.35 0.10 300)',
      client: 'Techpolitan',
      role: 'Business Development · Project Manager · 3D Design',
      team: 'PT. Walden Global Service (parent) · Techpolitan (in-house)',
      period: '2022 — 2023',
      platform: 'Mobile (Android & iOS)',
      discipline: ['Mobile', 'Metaverse', 'Social', 'Brand Integration'],
      tools: 'Blender, Unity, Internal PM Tool',
      metric: '—',
      metricLabel: 'Brand integration platform',
    },
    tags: 'mobile · social metaverse',
    heroSvg: 'generic',
    problem: {
      title: 'Brands lived in silos. Users lived on feeds.',
      statValue: 1, statSuffix: '', statUnit: 'Ecosystem',
      description: 'Techpolitan is a mobile Metaverse project to integrate brands under PT. Walden Global Service into one social-ecosystem to promote and sell digital goods and services. The challenge was to create a unified virtual space where multiple brands could coexist, interact with users, and drive engagement — all within a mobile-first experience.',
      constraints: [
        'Must integrate multiple brands under one parent company into a cohesive experience',
        'Mobile-first — smooth performance on mid-range Android and iOS devices',
        'Social ecosystem that promotes and sells digital goods and services',
        'Virtual spaces that feel engaging, not like a digital catalogue',
      ],
      summary: 'The platform needed to make brand interaction feel social and spatial — not transactional.',
    },
    process: {
      title: 'From brand audit to social ecosystem.',
      sub: 'Wearing three hats: business development, project management, and 3D design.',
      steps: [
        { n: '01', label: 'Brand ecosystem mapping', body: 'Audited all brands under PT. Walden Global Service to understand their digital presence, product offerings, and target audiences. Identified overlaps and gaps that a unified metaverse could address.' },
        { n: '02', label: 'Business development', body: 'Defined the business case for a unified social-ecosystem: how integrated brand presence could drive cross-selling, increase engagement time, and create new digital goods revenue streams.' },
        { n: '03', label: '3D environment design', body: 'Designed the virtual spaces in Blender — brand zones, social areas, and marketplace environments. Each space had to feel distinct to the brand while cohesive within the overall metaverse aesthetic.' },
        { n: '04', label: 'Project management', body: 'Managed the development pipeline using internal PM tools. Coordinated across brand stakeholders, engineering, and creative teams to maintain scope and timeline alignment.' },
        { n: '05', label: 'Integration & launch', body: 'Integrated brand experiences into the Unity-built mobile app. Ensured consistent performance across devices while maintaining visual quality that represented each brand accurately.' },
      ],
    },
    solution: {
      title: 'One social ecosystem for multiple brands.',
      heroLabels: ['Brand Zones', 'Social Space', 'Marketplace'],
      features: [
        { tag: 'Integration', title: 'Unified brand presence.', body: 'Multiple brands under PT. Walden Global Service brought together in one cohesive virtual space. Each brand maintains its identity while users flow naturally between experiences.', accentKey: 'green' },
        { tag: 'Commerce', title: 'Digital goods & services.', body: 'A marketplace for promoting and selling digital goods and services within the social ecosystem. Commerce feels native to the experience, not bolted on.', accentKey: 'yellow' },
        { tag: 'Social', title: 'Social-ecosystem design.', body: 'Users don\'t just browse brands — they socialize around them. The spatial design encourages discovery through social interaction rather than search and browse.', accentKey: 'pink' },
      ],
    },
    gallery: [
      { label: 'Brand zone — virtual space' },
      { label: 'Social area — user interaction' },
      { label: 'Marketplace interface' },
      { label: '3D environment design (Blender)' },
      { label: 'Mobile app — brand integration' },
    ],
    outcome: {
      title: 'A mobile metaverse that unified a brand ecosystem.',
      stats: [
        { val: 1, suffix: '', label: 'Unified social ecosystem', accentKey: 'accent' },
        { val: 3, suffix: '', label: 'Roles held simultaneously', accentKey: 'green' },
        { val: 2, suffix: '', label: 'Platforms (Android & iOS)', accentKey: 'yellow' },
      ],
      impactQuote: '"Techpolitan proved that brand integration works best when it feels social — not transactional."',
      impactNote: 'Built for PT. Walden Global Service · 2022–2023',
    },
    reflection: {
      title: 'What I learned.',
      cards: [
        { heading: 'Three hats at once.', body: 'This was the first project where I held business development, project management, and 3D design roles simultaneously. The breadth taught me how every design decision has a business consequence — and vice versa.' },
        { heading: 'Brand cohesion is spatial.', body: 'Integrating multiple brands into one space isn\'t just a visual challenge — it\'s an information architecture problem. Users need to understand where they are and why brands coexist without it feeling forced.' },
        { heading: 'Mobile metaverse constraints.', body: 'Building a 3D social space for mobile taught me how much visual quality you can achieve within performance budgets — and where the hard limits are that no optimization can bypass.' },
        { heading: 'Internal tools shape pace.', body: 'Using internal PM tools instead of industry-standard ones meant adapting workflows to the tool, not the other way around. It reinforced that process design is as important as product design.' },
      ],
    },
  },

};

window.ALL_PROJECT_CONTENT = ALL_PROJECT_CONTENT;
window.PROJECT_CONTENT = ALL_PROJECT_CONTENT[window.PROJECT_SLUG] || ALL_PROJECT_CONTENT.parachute;
